name: Automated API tests using Postman CLI

on:
  push:
    branches:
      - "*"
    paths:
      - "src/**/*"
      - "postman/collections/**/*"
      - "postman/fixture/**/*"
  pull_request:
    branches:
      - "*"

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest   

    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Initialize containers
        run: |
          docker compose -f ${{ github.workspace }}/postman/docker-compose.yaml up -d

      - name: Wait for API to be ready
        run: |
          until curl -sSf http://localhost:5000/monitoring/liveness; do
            sleep 5
          done

      - name: Run API tests
        run: |
          for file in "${{ github.workspace }}/postman/collections"/*.json; do
            postman collection run "$file" --integration-id "154477-${{ github.run_id }}"
          done
